### ISSUE TITLE
Installation: Procedure principle?

### ISSUE THREAD

**Issue by schittli** [jboxberger/synology-gitlab#12]
Good morning

I assume that this synology-gitlab package requires the original Synology Package Docker-GitLab as its base... therefore, is this procedure right?:

1. Install the original Synology Package Docker-GitLab
2. Install this synology-gitlab package by starting Synology DSM » Package Manager » Manual install and then select latest.spk

I ask because I get this error on DSM 6.1-15047 Update 1:
_This package is not supported on the platform of DiskStation or is incompatible with the current DSM version._

And maybe it's worth looking into your source and make it working again :-)

Thanks a lot for your work!
kind regards,
Thomas

**Comment by jboxberger** [comment]
Hi Thomas,
this should not happen...

This is a standalone Pakage and don't require the original one as base.

I haven't updated to 6.1-15047 Update 1 yet... i will check it on this Weekend and give you feedback.

Thanks for your Issue.

**Comment by schittli** [comment]
Hi Juri

Thank you very much for your fast answer, clarification and that you'll check it!, 
if the sun is shining on the weekend, please feel free to enjoy it and to check it on another day :-)

Thanks a lot for your help.
Kind regards, Thomas

**Comment by jboxberger** [comment]
Hi Thomas,

i've checked the update procedure today without any problems. I think it is a architecture issue. Which synology do you have?

Kind Regards.

**Comment by schittli** [comment]
Hi Jury,

thank you very much for your support and that you take the time to test it!
I'm very sorry that I've not noted the Synology Model, I've learned last night that there are important differences...

I use the DS3617xs which has this CPU: **INTEL Xeon D-1527**

I've installed opkg, therefore I could install a compiler. Would this help, so that I could compile your Package and upload the result to github?

Kind regards, Thomas

**Comment by jboxberger** [comment]
Ah ok i see this is the broadwell architecture. I have no access to such device to test it. I've made a Package for you which includes your architecture so you can install it.

If you have the choice, i reccommend you to uninstall the original Gitlab Package before because it is very old and have some old config struggels. When you have to update the old package i highly recommend you to backup your data. Here is a HowTo: https://github.com/jboxberger/synology-gitlab#howtos

The Package i attached is the latest Package from this repo, i only added your architecture to the Package information. I checked the scripts with other INTEL based architectires - they are all the same - so i think this should work fine. I also do not expect any problems on the docker side.

**_Please see this package as experimental._** If you can confirm that this package works i can add your architecture to the list. 

There is no compilation requred since there is no "magic" about this. In short there is a synology "WebAPI" for the wizzard and some "pre" "post" "after" "start/stop" shell scripts and i use the already configured and compiled "sameersbn/gitlab" container. So theoretically you can just add the container to your docker, make the config manually and you are good. 

But for someone not familliar with docker ruby and gitlab runtime environment this isn't as easy as it sounds, so this package is just an "easy entry" in the docker gitlab world :-)

Kind Regards

**Experimental Broadwell Package:** [GitLab-8.16.6.broadwell.zip](https://github.com/jboxberger/synology-gitlab/files/819379/GitLab-8.16.6.broadwell.zip)

**Comment by jboxberger** [comment]
Hey Thomas,

have you some feedback for me?

Kind Regards

**Comment by schittli** [comment]
Good morning Jury
Unfortunately, I had a case of emergency and was not able to do anything, but I'm very confident that I'll get a chance this weekend.

I'll send you a feedback asap and I'm very grateful for your great support. 
I'm very sory, that I was not able to answer immediately after you've sent me the new package.

Kind regards, Thomas

**Comment by jboxberger** [comment]
No Problem, take your time! 
Thanks for helping to improve this Package. 👍

**Comment by schittli** [comment]
Good evening Jury
I'm very sorry for my long delay, sometimes it's hard to plan the days...

Finally, I was able to test your 'Experimental Broadwell Package' and the installation works perfectly, gitlab is up & running stable :-)

Thank you very much for your great support.

Kind regards, Thomas

**Comment by jboxberger** [comment]
Hi Thomas,

thank you for your feedback, i added the broadwell archticeture to the setup in the new 9.1.1 version.
I happy i could help you.

Kind Regards
