### ISSUE TITLE
Option SIDEKIQ_CONCURRENCY is not respected on start

### ISSUE THREAD

**Issue by helmut-steiner** [jboxberger/synology-gitlab#16]
Setting the option SIDEKIQ_CONCURRENCY as described in https://github.com/sameersbn/docker-gitlab#available-configuration-parameters doesn't have any effect on the number of sidekiq tasks.

Settings:
![gitlab1capture](https://user-images.githubusercontent.com/8708898/26853710-5d930cde-4b13-11e7-92b4-755c2cb60f1d.PNG)

Initialization during startup (see the second process which is called with the -c 25 option):
![gitlab2capture](https://user-images.githubusercontent.com/8708898/26853709-5d8a75b0-4b13-11e7-88f4-a29353f59a1b.PNG)

It worked with the last 8.x version but since 9.x it always starts with 25 workers which consumes a lot of cpu on my old Synology NAS.

**Comment by jboxberger** [comment]
Hello Helmut,

i checked it and can reproduce it, but i can't help you out, since it's an docker container issue. I use the same container as the original synology package is using "sameersbn/docker-gitlab". So you need to open your issue there. I found something similar, but this should already be solved, maybe you can re-open it. 

https://github.com/sameersbn/docker-gitlab/issues/174

**Comment by helmut-steiner** [comment]
Thank you for testing and confirming the bug!
Seems as it has been reintroduced somewhen in the 9.x version as it was working before...
Have a great week!

PS: I am thinking about refining the installation procedure with more options... Are there any resources you recommend for getting started with Synology package creation/adaption? I.e. I want to help you maintaining this package if that's okay for you.
