### ISSUE TITLE
How to update a running package on Synology

### ISSUE THREAD

**Issue by saschafoerster** [jboxberger/synology-gitlab#17]
Last time, when I was installing for testing purposes, the update via uploading the fresh package in the synology package manager led to a broken gitlab-installation. Would be nice, if you could describe in a little more detail, which are the correct steps for updating. Thanks!

**Comment by jboxberger** [comment]
Hi saschafoerster,
what exactly went wrong? There shouldn't be any broken gitlab installation. :-)


Your Gitlab Data is under /volume1/docker/gitlab an will be re-used when new gitlab is up and running. Also your database will be re-used and updated once the updated gitlab package is up and running. 

The Update Process is straght forward. Downlaod the latest.spk, go to your packet manager and make a manual installation, thats exactly the way you did it, and WAIT UNTIL END. The Update my take very long because the new gitlab Package needs to be downloaded (about 500MB) first. If you connection or the docker server are lame... then you need to be very patient. You also should leave the settings in the wizzard unchanged or change them only when you know what your are doing. Giving here wrong DB credeantials may make the gitlab package break.

Could you please provide me more information about what went wrong. Then i may help you.

Kind Regards

**Comment by saschafoerster** [comment]
Indeed, after trying it with the newest package (and after deleting an older package) and after adding some more RAM to the NAS, the old database and filebase is visible again! Great. 
So next time I just upload, wait (some more) or I will give you a bugreport before deleting the old installation. Thank you for this package, makes using the newest gitlab on Synology a breeze!
