### ISSUE TITLE
Adding a 4096 gpg key fails

### ISSUE THREAD

**Issue by agherzan** [jboxberger/synology-gitlab#22]
It seems like the database is not allowing such a big entry:
```
 Parameters: {"utf8"=>"✓", "authenticity_token"=>"XXX", "gpg_key"=>"[FILTERED]"}
Completed 500 Internal Server Error in 2195ms (ActiveRecord: 16.9ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Data too long for column 'key' at row 1: INSERT INTO `gpg_keys`
```

**Comment by jboxberger** [comment]
Hi agherzan, sorry for my late reply. 
Yes it's a database issue, but it's a GitLab Bug and i can't fix anything about that because i take the whole GitLab package as it is without any modifications from docker Hub.

Which Version is affected? Maybe i can help find a solution even if this reply comes late. 
Kind Regards

**Comment by agherzan** [comment]
I can't remember what version i was using because due to these bugs a dropped the setup. Maybe I'll try to replicate it soon.

**Comment by jboxberger** [comment]
I got more information on this, GitLab not really like MariDB and have several incompatibillities. also there is i problem with the utf8 and utf8mb4 and also the ROW_FORMAT. At the moment there is nothing i can do about it. I will release a 10.3.x version (hopefully) soon. 10.3.x breaks the database because of the upper reasons, so i have to convert the database. Please try it the again, hopefully this will work then.

Kind reagds

**Comment by agherzan** [comment]
Let me understand, is 10.3 version not using mariadb?

**Comment by jboxberger** [comment]
No of course GitLab 10.3 uses maria DB but because of the shema definition missmatch since 10.2.5 it's not possible to install GitLab >10.2.5 on MariaDB 10 because of the ROW_FORMAT=COMPACT which should be ROW_FORMAT=DYNAMIC. There is a workaround by setting this in the my.cnf and altering all tables but this works only for the update scenario. On a clean install Gitlab fails to create the schema because the implicit ROW_FORMAT is missing in the create schema script and by default its ROW_FORMAT=COMPACT. 

I don't know why synology is betting with MariaDB on a dead horse but GitLab says clearly:

- PostgreSQL (highly recommended)
- MySQL/MariaDB (strongly **discouraged**...

See: https://docs.gitlab.com/ce/install/requirements.html#database

On the long term i am working on a own package and i will use PostgreSQL, the hardest thing will be the data migration.

**Comment by agherzan** [comment]
Any updates on this? I'd like to test 10.3

**Comment by jboxberger** [comment]
Hello agherzan,
i tested already the 10.4.2 but with the same result. It still breaks on the Gitlab MariaDB migrate script. 
I update Regulary the Status on the main Page ([here](https://github.com/jboxberger/synology-gitlab#dsm-614-15217)).

You can checkout the PostgreSQL package here:
https://github.com/jboxberger/synology-gitlab-jboxberger/releases

Kind Regards

**Comment by jboxberger** [comment]
Hello agherzan,

this package is "dead" because of the dropped MySQL/MariaDB Support. You can migrate to my new package. The gpg key should work fine on the new package. 

More info about the new package and migration you can get here.
[https://github.com/jboxberger/synology-gitlab-jboxberger.](https://github.com/jboxberger/synology-gitlab-jboxberger)

Kind Reagrds
Juri
