### ISSUE TITLE
[FYI] A potential solution to missing gitlab container after installing

### ISSUE THREAD

**Issue by evianzhow** [jboxberger/synology-gitlab#23]
Got the same situation with https://github.com/jboxberger/synology-gitlab/issues/19

I've downloaded the latest (10.0.2) and try the fresh install. The official one raise the same issue, gitlab container missing and couldn't start. Try the official default configuration and everything works fine. There must be something wrong with mine. 

I've been investigating and finally, found out that binding SSH container port 22 to host 22 is unprivileged and the Web API will return an error. After fixed that, the `synology_gitlab` container can be successfully created.

But the container still can't run, which I mean got stopped after a few seconds. I found out that I left the environment variable `MARIADB_PASS ` empty, so the initial SQL command never got executed. By manually typing them under `phpmyadmin`, then the container started running.

**Comment by jboxberger** [comment]
Hi sorry for my late reply, i've not forgotten about you. I was working since november on a new more stable package type to prevent many issues during the installation, since the DSM and Package Synology APIs are in ongoing change. 

I will release a new Package Type (which i am working already about 3 Moths on) in a few weeks which should solve a bunch of problems. The new Package will build dynamicly from the stock package, this should prevent many future issues.

Hope this helps. Kind Regards

**Comment by jboxberger** [comment]
Hi EvianZhow,

the new package 10.2.5 is released and this should solve your problem. The new package brings also already the docker container with itself (All-In-One Package) so the install should not be affected by download errors/issues during update anymore.

Kind Regards
