### ISSUE TITLE
Really slow response

### ISSUE THREAD

**Issue by Satris404** [jboxberger/synology-gitlab#29]
Hi,

I installed your last version of Gitlab (10.2.5) and was able run the image. When I try to access Gitlab, the response is so slow that I always get the timeout page. Sometimes I can get to the log in page, but can't go further as I get the timeout page again. The running image only takes 4% of my CPU and about 800mb out of the 2gb ram so it's not a lack of ressources. I've tried to restart the image but still.
Here's the log, if you need other info just ask. 
[synology_gitlab.zip](https://github.com/jboxberger/synology-gitlab/files/1746887/synology_gitlab.zip)

I have installed MariaDB version 10.0.32 and my synology DS218+ is running on DSM 6.1.5.

Thank you

**Comment by jboxberger** [comment]
Hi Satris404,
i think 2GB is the Problem here, thou it is not shown as compeltly used. Have you tried to give it more time during conbtainer initialization? 20 Minutes or so?
https://docs.gitlab.com/ce/install/requirements.html#memory

![grafik](https://user-images.githubusercontent.com/1545845/36565482-e1afac5e-1820-11e8-8976-bb70ad131598.png)

Kind Regards

**Comment by Satris404** [comment]
Hi,

Thank you for your fast answer. Yes, I did let it initialize for a long moment. At some point, it was faster and I could login, but I still got timeout page sometimes. As it is not optimal with 2GB of RAM, I decided to go with Go-Gitea instead. It is far less memory demanding and works perfectly.

Samuel

**Comment by jboxberger** [comment]
Ok for Timeouts you can inrease the UNICORN_TIMEOUT environment variable but if the system is too slow, this makes no sence. Gitlab is really heavy. 

Kind Reagrds
