### ISSUE TITLE
gitlab.rb - external_url

### ISSUE THREAD

**Issue by TonySqrd** [jboxberger/synology-gitlab#35]
Not an issue. More like a question.  Any way to configure the external URL? ref: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template

I am running gitlab behind a reverse proxy and the emails have a url that is not accessible from outside.
Thanks 
Tony

**Comment by jboxberger** [comment]
Hi Tony,

the external URL is usually set during the Setup Routine on the first install. If you want to change the url later you can do it by changing the docker GITLAB_HOST. Since this container is not based on the omnibus package, you can not use directly `external_url`. 

Maybe you can find another solution here https://hub.docker.com/r/sameersbn/gitlab/#available-configuration-parameters

To set the ENVIRONMENT variable you have to stop the gitlab package and change it in you synology docker app.

![image](https://user-images.githubusercontent.com/1545845/59715462-348a7080-9214-11e9-8b44-d4b0bac3812a.png)

Kind Regards
