### ISSUE TITLE
Updating to latest

### ISSUE THREAD

**Issue by AntoineConffx** [jboxberger/synology-gitlab#40]
Would it be possible to get the latest gitlab version ?
I could open up a pull request and do it myself if you could share any instructions on how to build it

**Comment by jboxberger** [comment]
Hi AntoineConffx,

i've added the [Build Instructions](https://github.com/jboxberger/synology-gitlab#build-instructions) to the README. Please let me know if it worked for you.

The Update i de facto just a change of 2 lines and a docker image pull. The testing takes the most time so it takes some time until i am done.

You ca do an "latest" on Demand package by the replacing the Version with "latest". This gives you a small SPK which pulls the latest docker image every time you install it. But you really need to know what you are doing, because this can break your gitlab. It's not he installation routine, its gitlab itself which breakes from time to time. Thats why i publisch only pretested releases.

Hope this helps.

Kind Regards

**Comment by AntoineConffx** [comment]
Hey jboxberger,
I'd like to first say thanks for doing this :)

If you have an estimate on when the next update comes in I'd be willing to wait if it would be tested correctly, but I might just give it a shot, and will re-open this if I have any issues

**Comment by jboxberger** [comment]
I will make the 12.7.5 the next few days :-)

**Comment by AntoineConffx** [comment]
Awesome, Thank you again !

**Comment by jboxberger** [comment]
You are Welcome. The 12.7.5 update is online.

**Comment by AntoineConffx** [comment]
Awesome, Thanks again.
