### ISSUE TITLE
Update to 12.9.x

### ISSUE THREAD

**Issue by helmut-steiner** [jboxberger/synology-gitlab#42]
Hey Juri,
I hope you are doing fine during these uncertain times! I wondered if you are still maintaining this repo? If so it would be great to get an update to a newer version to be on par with Sameer's docker repo.
All the best,
Helmut

**Comment by FoxD7** [comment]
Hi Juri, Hi Helmut,
I can hardly wait for the new version ;) If you need help i would be happy to help.
...Also in German ;)
Looking forward to hear from you.

>> Fox

**Comment by jboxberger** [comment]
Hello guys,

i am fine thanks. I will do the Update today so it will be available by tomorrow.

> Hi Juri, Hi Helmut,
> I can hardly wait for the new version ;) If you need help i would be happy to help.
> ...Also in German ;)
> Looking forward to hear from you.
> 
> > > Fox

If you do not want to wait for me to publish a release, i recommend you to checkout the Build Instructions. I've fully automated the process so there are only  2 Lines of code to change and call the Build script. This way you're fully independent. I do not do the updates automatically because in the past there were some builds from git lab which broke on data migration. So i do a lot of testing before  uploading a release.

Build instructions:
https://github.com/jboxberger/synology-gitlab#build-instructions

Kind Regards!

**Comment by jboxberger** [comment]
Sorry guys, i did not make it this night. But i have it on my list an will deliver this week. Sorry for let you wait. Kind Regards

**Comment by helmut-steiner** [comment]
Hey Juri,
Don't worry/stress yourself! I am glad you are okay and still maintaining this repo.
Stay safe and healthy!
Kind regards, Helmut

**Comment by jboxberger** [comment]
Hello guys,

i've uploaded a new release and rebuild the "build" process. The Build Process is now fully automated and should be running on Arch and Ubuntu systems. All required packages for the build will be installed automatically (this process is not final yet, but it should be working by now).

Just call the build script. :-)
![grafik](https://user-images.githubusercontent.com/1545845/79678139-700d1700-81f8-11ea-9d87-0caa3f291260.png)

I also updated the [build instructions](https://github.com/jboxberger/synology-gitlab#build-instructions).


Kind Regards
