### ISSUE TITLE
DSM7 experimental

### ISSUE THREAD

**Issue by tkirkland** [jboxberger/synology-gitlab#52]
Just to let you be aware, I'm running the latest security patch of DSM 7 on RS2421+ and when manually pushing the SPK, the UI says it is not compatible.

Appreciate your work!

**Comment by jboxberger** [comment]
yes thank you very much, i will release hopefully this or next week a complete standalone gitlab-ce package for DSM7. After that i will explore a migration path so you can migrate easily.
It will be possible to update the gitlab-ce image without waiting for a new release, and you will be able run infinte separate instances of gitlab, so you can test all your migrations and updates before :-).

I am very glad to get rid of any original synology gitlab package restrictions :-)

Stay tuned, this will be great.

**Comment by jboxberger** [comment]
This is not possible to run this package on DSM7 and because of that its discontinued. I will update the readme asap.

But as promised, he you go with the new version. Hope you like it. I recommend the advanced version, so you can update the package yourself anytime.

https://github.com/jboxberger/synology-gitlab-ce

Kind Regards
