### ISSUE TITLE
Cannot update or jnstalm

### ISSUE THREAD

**Issue by Finkman** [jboxberger/synology-gitlab#6]
I'd tried to update to the latest version of the gitlab package. Unfortunately, the installation breaks and gitlab cannot start.
Only the redis container is visible and running. When starting gitlab from the package manager (which minds gitlab is correctly installed) the cpu load goes up for a short time, but the status of the package falls back to "stopped".

I already tried to deinstall the package (while keeping the data) and reinstall it. But the behaviour stays the same.

No I stuck with a broken gitlab installation.

**Comment by jboxberger** [comment]
Just reinstall it.

Am 20.08.2016 00:47 schrieb "Finkman" <notifications@github.com>:

**Comment by jboxberger** [comment]
Sorry i am on holiday now and not in the near my environment. I give you
detailed feedback on wendsday. Please be patient. When you keep the
database nothing is lost. But make a backup for safety. Stay tuned until
wendsday. If youre german maybe i can call you to go through all
possibilities. Kind regards

Am 20.08.2016 20:23 schrieb "Juri Boxberger" juri.boxberger@gmail.com:

Just reinstall it.

Am 20.08.2016 00:47 schrieb "Finkman" notifications@github.com:

**Comment by Finkman** [comment]
I've reinstalled it several times, but it ended always the same.

I knew, that that is held in the mysql and in the mounted folders. So I successfully installed gitlab through the docker hub and it worked from the first minute. Now, updating is easier.
Updating with your package sometimes loses the db settings.

So, I stopped using your package, but it was very helpful. Thanks a lot.

**Comment by jboxberger** [comment]
Ok now i can reproduce your issue. Since Gitlab 8.10.7 new config Settings (_GITLAB_SECRETS_SECRET_KEY_BASE_ and _GITLAB_SECRETS_OTP_KEY_BASE_) are required so you need to implement them in the _postinst_ and _postupgrade_. I've done this now and the update to 8.11 works fine. 

My Goal ist to help to get a more UpToDate Version of Gitlab for everyone. Not erveryone can handle Docker Images and knows how to configure GitLab to get it running. So this Module is more like a "Starter-Pack". Advanced Users install GitLab native to increase the performance :-)

I'm glad that my work was helpfull for you! 

Kind Regards
